// Generated by gencpp from file localization/MyServiceMessage.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_MESSAGE_MYSERVICEMESSAGE_H
#define LOCALIZATION_MESSAGE_MYSERVICEMESSAGE_H

#include <ros/service_traits.h>


#include <localization/MyServiceMessageRequest.h>
#include <localization/MyServiceMessageResponse.h>


namespace localization
{

struct MyServiceMessage
{

typedef MyServiceMessageRequest Request;
typedef MyServiceMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MyServiceMessage
} // namespace localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::localization::MyServiceMessage > {
  static const char* value()
  {
    return "920ca5ca095e1b5230fc32da338a974c";
  }

  static const char* value(const ::localization::MyServiceMessage&) { return value(); }
};

template<>
struct DataType< ::localization::MyServiceMessage > {
  static const char* value()
  {
    return "localization/MyServiceMessage";
  }

  static const char* value(const ::localization::MyServiceMessage&) { return value(); }
};


// service_traits::MD5Sum< ::localization::MyServiceMessageRequest> should match
// service_traits::MD5Sum< ::localization::MyServiceMessage >
template<>
struct MD5Sum< ::localization::MyServiceMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::localization::MyServiceMessage >::value();
  }
  static const char* value(const ::localization::MyServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::localization::MyServiceMessageRequest> should match
// service_traits::DataType< ::localization::MyServiceMessage >
template<>
struct DataType< ::localization::MyServiceMessageRequest>
{
  static const char* value()
  {
    return DataType< ::localization::MyServiceMessage >::value();
  }
  static const char* value(const ::localization::MyServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::localization::MyServiceMessageResponse> should match
// service_traits::MD5Sum< ::localization::MyServiceMessage >
template<>
struct MD5Sum< ::localization::MyServiceMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::localization::MyServiceMessage >::value();
  }
  static const char* value(const ::localization::MyServiceMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::localization::MyServiceMessageResponse> should match
// service_traits::DataType< ::localization::MyServiceMessage >
template<>
struct DataType< ::localization::MyServiceMessageResponse>
{
  static const char* value()
  {
    return DataType< ::localization::MyServiceMessage >::value();
  }
  static const char* value(const ::localization::MyServiceMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCALIZATION_MESSAGE_MYSERVICEMESSAGE_H
