// Generated by gencpp from file send_goals/NaviServiceMessage.msg
// DO NOT EDIT!


#ifndef SEND_GOALS_MESSAGE_NAVISERVICEMESSAGE_H
#define SEND_GOALS_MESSAGE_NAVISERVICEMESSAGE_H

#include <ros/service_traits.h>


#include <send_goals/NaviServiceMessageRequest.h>
#include <send_goals/NaviServiceMessageResponse.h>


namespace send_goals
{

struct NaviServiceMessage
{

typedef NaviServiceMessageRequest Request;
typedef NaviServiceMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NaviServiceMessage
} // namespace send_goals


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::send_goals::NaviServiceMessage > {
  static const char* value()
  {
    return "920ca5ca095e1b5230fc32da338a974c";
  }

  static const char* value(const ::send_goals::NaviServiceMessage&) { return value(); }
};

template<>
struct DataType< ::send_goals::NaviServiceMessage > {
  static const char* value()
  {
    return "send_goals/NaviServiceMessage";
  }

  static const char* value(const ::send_goals::NaviServiceMessage&) { return value(); }
};


// service_traits::MD5Sum< ::send_goals::NaviServiceMessageRequest> should match
// service_traits::MD5Sum< ::send_goals::NaviServiceMessage >
template<>
struct MD5Sum< ::send_goals::NaviServiceMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::send_goals::NaviServiceMessage >::value();
  }
  static const char* value(const ::send_goals::NaviServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::send_goals::NaviServiceMessageRequest> should match
// service_traits::DataType< ::send_goals::NaviServiceMessage >
template<>
struct DataType< ::send_goals::NaviServiceMessageRequest>
{
  static const char* value()
  {
    return DataType< ::send_goals::NaviServiceMessage >::value();
  }
  static const char* value(const ::send_goals::NaviServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::send_goals::NaviServiceMessageResponse> should match
// service_traits::MD5Sum< ::send_goals::NaviServiceMessage >
template<>
struct MD5Sum< ::send_goals::NaviServiceMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::send_goals::NaviServiceMessage >::value();
  }
  static const char* value(const ::send_goals::NaviServiceMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::send_goals::NaviServiceMessageResponse> should match
// service_traits::DataType< ::send_goals::NaviServiceMessage >
template<>
struct DataType< ::send_goals::NaviServiceMessageResponse>
{
  static const char* value()
  {
    return DataType< ::send_goals::NaviServiceMessage >::value();
  }
  static const char* value(const ::send_goals::NaviServiceMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEND_GOALS_MESSAGE_NAVISERVICEMESSAGE_H
