(cl:defpackage send_goals-srv
  (:use )
  (:export
   "NAVISERVICEMESSAGE"
   "<NAVISERVICEMESSAGE-REQUEST>"
   "NAVISERVICEMESSAGE-REQUEST"
   "<NAVISERVICEMESSAGE-RESPONSE>"
   "NAVISERVICEMESSAGE-RESPONSE"
  ))

